server:
  port: 8080

spring:
  application:
    name: resilient-secure-http-gateway

management:
  endpoints:
    web:
      exposure:
        include: health,metrics

app:
  security:
    jwt:
      secret: "change-me-super-long-secret-key-please-change-for-real-use"
      expiration-minutes: 30
    pepper: "pepper-change-me"
  external-api:
    base-url: "http://localhost:8080/external/v1"
    connect-timeout-ms: 2000
    read-timeout-ms: 3000
    user-agent: "java-course-gateway/1.0"

resilience4j:
  circuitbreaker:
    instances:
      externalApi:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
  ratelimiter:
    instances:
      externalApi:
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 0s

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} trace=%X{traceId} - %msg%n"
