name: Build

on:
  push:
    branches: ["*"]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v3 
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          
      - name: Cache local repository for faster builds
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            
      - name: Run Maven Package
        run: mvn clean package --batch-mode --update-snapshots

      - name: Check Build Result
        if: failure()
        run: echo "Build failed!"
        
      - name: Upload Artifact
        if: success() && startsWith(github.ref, 'refs/pull/')
        uses: actions/upload-artifact@v4
        with:
          name: maven-build-output
          path: target/*.jar
