name: Show Date and Time

on:
  push:
    branches:
      - '*'
  pull_request:
    types: [opened, reopened, synchronized]

jobs:
  date_and_time:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Display current date and time
        run: |
          echo "Current date and time is: $(date '+%F %T')"
