name: My JOB

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  display_datetime_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Display current datetime
        run: |
          echo "Current date and time is $(date)"
